default:
  image: golang:1.12
  before_script:
    - mkdir -p .cache/gocache
    - export PATH=$PATH:$CI_PROJECT_DIR/.cache/bin/
    - export GOPATH="$CI_PROJECT_DIR/.cache"
 
stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  cache:
    key: lint-cache
    paths:
      - .cache
  script: 
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint
    - .cache/bin/golangci-lint run --disable-all --enable=vet --enable=gofmt --deadline=600s ./...
    - export GOCACHE=$CI_PROJECT_DIR/.cache/gocache
    - make test

legacy-tests:
  stage: test
  cache:
    key: legacy-cache
    paths:
      - .cache
  except:
    - schedules
  script: 
    - make test-long pkgs="./node ./node/api ./node/api/server" run=.

package-tests:
  stage: test
  cache:
    key: package-cache
    paths:
      - .cache
  except:
    - schedules
  script: 
    - make test-long run=. pkgs="./build ./cmd/siac ./cmd/siad ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/renter/siadir ./modules/renter/siafile ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./sync ./types"

siatest-tests:
  stage: test
  cache:
    key: integration-cache
    paths:
      - .cache
  except:
    - schedules
  script:
    - make test-long run=. pkgs="./siatest ./siatest/consensus ./siatest/daemon ./siatest/gateway ./siatest/host ./siatest/miner ./siatest/transactionpool ./siatest/wallet"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-renter-tests:
  stage: test
  except:
    - schedules
  cache:
    key: siatest-renter-tests-cache
    paths:
      - .cache
  script:
    - make test-long run=. pkgs="./siatest/renter ./siatest/renter/contractor ./siatest/renter/hostdb ./siatest/renterhost"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

legacy-tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script: 
    - make test-vlong pkgs="./node ./node/api ./node/api/server" run=.
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

package-tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script: 
    - make test-vlong run=. pkgs="./build ./cmd/siac ./cmd/siad ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./sync ./types"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-vlong run=. pkgs="./siatest ./siatest/consensus ./siatest/daemon ./siatest/gateway ./siatest/host ./siatest/miner ./siatest/transactionpool ./siatest/wallet"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

siatest-renter--tests-nightly:
  stage: test
  only:
    - schedules
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  script:
    - make test-vlong run=. pkgs="./siatest/renter ./siatest/renter/contractor ./siatest/renter/hostdb ./siatest/renterhost"
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

deploy:
  stage: deploy
  only:
    refs:
      - master@NebulousLabs/Sia
  artifacts:
    name: "Binaries"
    paths:
      - $CI_PROJECT_DIR/artifacts
  script: 
    - ./deploy.sh "$NIGHTLY_SIGNING_KEY"
